export const ACCOUNT_OPEN = "ACCOUNT_OPEN"
export const ACCOUNT_OPEN_IN_PROGRESS = "ACCOUNT_OPEN_IN_PROGRESS"
export const ACCOUNT_OPEN_SUCCESS = "ACCOUNT_OPEN_SUCCESS"
export const ACCOUNT_OPEN_ERROR = "ACCOUNT_OPEN_ERROR"